name: Build and Deploy Go Application to Lambda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go mod download

      - name: Build for Linux amd64
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags lambda.norpc -o bin/main ./...

      - name: Zip for Lambda deployment
        run: |
          zip -j bootstrap.zip bin/main

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-deployment
          path: bootstrap.zip

  deploy:
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: lambda-deployment

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-north-1  # Replace with your Lambda function's region

      - name: Deploy to AWS Lambda
        run: |
          aws lambda update-function-code \
            --function-name RV-aplikace \
            --zip-file fileb://bootstrap.zip

      - name: Test Lambda function (optional)
        run: |
          aws lambda invoke --function-name RV-aplikace output.json && cat output.json
