name: Build and Package Go Application for Lambda

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.21.x'

      - name: Install dependencies
        run: go mod download

      - name: Build for Linux amd64
        run: |
          mkdir -p bin
          GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -tags lambda.norpc -o bin/main ./...

      - name: Zip for Lambda deployment
        run: |
          zip -j bootstrap.zip bin/main

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: lambda-deployment
          path: bootstrap.zip

      - name: Test
        run: go test -v ./...
