name: Build and Package Binary

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.x

      - name: Install dependencies
        run: go get -v ./...

      - name: Build the binary
        env:
          GOOS: linux
          GOARCH: amd64
          CGO_ENABLED: 0
        run: go build -tags lambda.norpc -o bootstrap main.go

      - name: Zip the binary
        run: zip function.zip bootstrap

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: lambda-function
          path: function.zip

